@startuml hierarchy

[矢呼首页] --> [登录]
[矢呼首页] --> [注册]

[登录] --> [用户信息管理]
[登录] --> [问答]
[登录] --> [接收通知]

[用户信息管理] --> [修改密码]
[用户信息管理] --> [删除用户]
[用户信息管理] --> [修改用户信息]

[问答] --> [问]
[问答] --> [答]

[问] --> [创建问题]
[问] --> [修改问题]
[问] --> [删除问题]

[答] --> [评论]
[答] --> [创建回答]
[答] --> [修改回答]
[答] --> [删除回答]

[评论] --> [发表评论]
[评论] --> [回复评论]

@enduml