@startuml resetpassword-class
package django.forms {
    class Form
}

package django.db.models {
    class Model
}

package forms {
    class UserForm {
        username
    }
    class UserPass {
        password1
        password2
    }
    class UserCode {
        usercode
    }

    UserForm --|> Form
    UserPass --|> Form
    UserCode --|> Form
}

package models {
    class ConfirmString

    ConfirmString --|> Model
}

@enduml